# Generated by Django 4.2.7 on 2024-01-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=255)),
            ],
        ),
    ]
